# Tomcat
server:
  port: 80

spring:
  application:
    # 应用名称
    name: lotus-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        #        namespace: 10
        file-extension: yml
        shared-configs:
          - redis.yml
          - nacos-discovery.yml
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

# 安全配置
security:
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /*/doc.html
      - /*/webjars/**
      - /*/swagger-resources
      - /*/favicon.ico
      - /*/v3/api-docs
      - /user-center/generateKey
      - /user-center/logout
      - /user-center/login

logging:
  file:
    path: ./logs/