spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

# 安全配置
security:
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /*/doc.html
      - /*/webjars/**
      - /*/swagger-resources
      - /*/favicon.ico
      - /*/v3/api-docs
      - /user-center/generateKey
      - /user-center/logout
      - /user-center/login